In [6]:
import numpy as np

In [13]:
a=np.arange(1,7,1)
b=np.arange(1,10).reshape(3,3)
c=np.arange(1,28).reshape(3,3,3)
print("1d ---------")
print(a)
print(a.shape)
print(a.size)
print(a.ndim)
print(a.dtype)
print(" ")
print("2d ---------")
print(b)
print(b.shape)
print(b.size)
print(b.ndim)
print(b.dtype)
print(" ")
print("3d ---------")
print(c)
print(c.shape)
print(c.size)
print(c.ndim)
print(c.dtype)




1d ---------
[1 2 3 4 5 6]
(6,)
6
1
int32
 
2d ---------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9
2
int32
 
3d ---------
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
(3, 3, 3)
27
3
int32


In [26]:
d = np.empty(3)
print(d)
f = np.full((3,5),5)
print(f)
g = np.zeros((3,5))
print(g)
h = np.ones((3,5))
print(h)

[4.60601562e-312 0.00000000e+000 4.94065646e-324]
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [31]:
e = np.arange(14,41)
print(e)

[14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37
 38 39 40]


In [35]:
e = np.arange(1,41).reshape(8,5)
print(e)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]]


In [39]:
e = np.arange(1,41).reshape(8,5)
print(e)

i=e.reshape(4,10)
print(i)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]]


In [49]:
i=e.reshape(4,10)
print(i)
print(i[:3,:4])
print(i[:3,4])
print(i[2:4, : ])
print(i[:,2:5])

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]]
[[ 1  2  3  4]
 [11 12 13 14]
 [21 22 23 24]]
[ 5 15 25]
[[21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]]
[[ 3  4  5]
 [13 14 15]
 [23 24 25]
 [33 34 35]]


In [50]:
j = i[i%2==1]
print(j)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]


In [57]:
k = i
k[i%2==0]=-1
k

array([[ 1, -1,  3, -1,  5, -1,  7, -1,  9, -1],
       [11, -1, 13, -1, 15, -1, 17, -1, 19, -1],
       [21, -1, 23, -1, 25, -1, 27, -1, 29, -1],
       [31, -1, 33, -1, 35, -1, 37, -1, 39, -1]])

In [64]:
l=np.random.randint(1,10,(5))
print(l)
m=np.random.randint(11,15,(5))
print(m)
n=np.append(l,m)
print(n)


[1 5 3 4 5]
[11 13 12 12 14]
[ 1  5  3  4  5 11 13 12 12 14]


In [89]:
ab=np.random.randint(1,10,10)
print(ab)
ab=ab.reshape(2,5)
print(ab)
ab=np.resize(ab,(2,2))
print(ab)

[7 2 2 4 8 4 2 4 5 6]
[[7 2 2 4 8]
 [4 2 4 5 6]]
[[7 2]
 [2 4]]


In [5]:
o = np.random.randint(16,40,12)
print(o)

p=np.sort(o)
print(p)

q=p[::-1]
print(q)

aa = np.flip(o)
print(aa)

[34 27 29 33 27 32 23 22 38 28 26 24]
[22 23 24 26 27 27 28 29 32 33 34 38]
[38 34 33 32 29 28 27 27 26 24 23 22]
[24 26 28 38 22 23 32 27 33 29 27 34]


In [101]:
arr=np.random.randint(1,50,(5,3))
print(arr)

print("*"*40)
arr=arr+4
print(arr)
print("*"*40)

arr=arr*2
print(arr)
print("*"*40)

arr=arr-3
print(arr)
print("*"*40)

arr=arr//2
print(arr)
print("*"*40)

[[10 32 23]
 [ 9 48 35]
 [10 18 17]
 [19 43 13]
 [39 27 27]]
****************************************
[[14 36 27]
 [13 52 39]
 [14 22 21]
 [23 47 17]
 [43 31 31]]
****************************************
[[ 28  72  54]
 [ 26 104  78]
 [ 28  44  42]
 [ 46  94  34]
 [ 86  62  62]]
****************************************
[[ 25  69  51]
 [ 23 101  75]
 [ 25  41  39]
 [ 43  91  31]
 [ 83  59  59]]
****************************************
[[12 34 25]
 [11 50 37]
 [12 20 19]
 [21 45 15]
 [41 29 29]]
****************************************


In [10]:
r = np.arange(1,10,1).reshape((3,3))
print(r)

s = np.arange(1,10,1).reshape((3,3))
print(s)

print("Addition---------------")
add = r+s
print(add)
print("Subtraction---------------")
sub = r-s
print(sub)
print("Multiplication---------------")
mult = r*s
print(mult)
print("division---------------")
div = r/s
print(div)

print(r.min())
print(r.max())


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Addition---------------
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Subtraction---------------
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Multiplication---------------
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
division---------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
1
9
